// <auto-generated />
using System;
using ClinicaApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicaApp.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    partial class ClinicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicaApp.Domain.AyudaDiagnostica", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdTipoEspecialista")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("RequiereEspecialista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AyudasDiagnosticas");
                });

            modelBuilder.Entity("ClinicaApp.Domain.ContactoEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Relacion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ContactosEmergencia");
                });

            modelBuilder.Entity("ClinicaApp.Domain.DetalleFacturaItem", b =>
                {
                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<int>("ItemOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("FacturaNumeroFactura")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Tipo", "NumeroOrden", "ItemOrden");

                    b.HasIndex("FacturaNumeroFactura");

                    b.ToTable("DetalleFactura");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Especialidad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Factura", b =>
                {
                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CedulaPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("CopagoPaciente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiasVigenciaPoliza")
                        .HasColumnType("int");

                    b.Property<int>("EdadPaciente")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinPoliza")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompaniaSeguro")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NombreMedicoTratante")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NombrePaciente")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NumeroPoliza")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("PolizaActiva")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalCubreAseguradora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalServicios")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NumeroFactura");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ClinicaApp.Domain.HistoriaClinicaEntrada", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CedulaMedico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaPaciente")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sintomatologia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoriaClinica");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Medicamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenAyudaDiagnosticaItem", b =>
                {
                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdAyudaDiagnostica")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IdTipoEspecialista")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NombreAyudaDiagnostica")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("OrdenMedicaNumeroOrden")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereEspecialista")
                        .HasColumnType("bit");

                    b.HasKey("NumeroOrden", "Item");

                    b.HasIndex("OrdenMedicaNumeroOrden");

                    b.ToTable("OrdenAyudaDiagnostica");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenMedica", b =>
                {
                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<string>("CedulaMedico")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CedulaPaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date");

                    b.HasKey("NumeroOrden");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenMedicamentoItem", b =>
                {
                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DuracionTratamiento")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IdMedicamento")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NombreMedicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("OrdenMedicaNumeroOrden")
                        .HasColumnType("int");

                    b.HasKey("NumeroOrden", "Item");

                    b.HasIndex("OrdenMedicaNumeroOrden");

                    b.ToTable("OrdenMedicamentos");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenProcedimientoItem", b =>
                {
                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<int>("Item")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IdProcedimiento")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("IdTipoEspecialista")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NombreProcedimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("OrdenMedicaNumeroOrden")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereEspecialista")
                        .HasColumnType("bit");

                    b.HasKey("NumeroOrden", "Item");

                    b.HasIndex("OrdenMedicaNumeroOrden");

                    b.ToTable("OrdenProcedimientos");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Paciente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("ContactoEmergenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("PolizaSeguroId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Cedula");

                    b.HasIndex("ContactoEmergenciaId");

                    b.HasIndex("PolizaSeguroId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaApp.Domain.PolizaSeguro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CompaniaSeguros")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVigenciaFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroPoliza")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PolizasSeguro");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Procedimiento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdTipoEspecialista")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("RequiereEspecialista")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Procedimientos");
                });

            modelBuilder.Entity("ClinicaApp.Domain.RegistroEnfermeria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CedulaPaciente")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemOrden")
                        .HasColumnType("int");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("SignosId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoItem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SignosId");

                    b.ToTable("RegistroEnfermeria");
                });

            modelBuilder.Entity("ClinicaApp.Domain.SignosVitales", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PresionArterial")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Pulso")
                        .HasColumnType("int");

                    b.Property<int>("SpO2")
                        .HasColumnType("int");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("SignosVitales");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Usuario", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Cedula");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ClinicaApp.Domain.DetalleFacturaItem", b =>
                {
                    b.HasOne("ClinicaApp.Domain.Factura", null)
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaNumeroFactura");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenAyudaDiagnosticaItem", b =>
                {
                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany()
                        .HasForeignKey("NumeroOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany("AyudasDiagnosticas")
                        .HasForeignKey("OrdenMedicaNumeroOrden");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenMedicamentoItem", b =>
                {
                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany()
                        .HasForeignKey("NumeroOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany("Medicamentos")
                        .HasForeignKey("OrdenMedicaNumeroOrden");
                });

            modelBuilder.Entity("ClinicaApp.Domain.OrdenProcedimientoItem", b =>
                {
                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany()
                        .HasForeignKey("NumeroOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaApp.Domain.OrdenMedica", null)
                        .WithMany("Procedimientos")
                        .HasForeignKey("OrdenMedicaNumeroOrden");
                });

            modelBuilder.Entity("ClinicaApp.Domain.Paciente", b =>
                {
                    b.HasOne("ClinicaApp.Domain.ContactoEmergencia", "ContactoEmergencia")
                        .WithMany()
                        .HasForeignKey("ContactoEmergenciaId");

                    b.HasOne("ClinicaApp.Domain.PolizaSeguro", "PolizaSeguro")
                        .WithMany()
                        .HasForeignKey("PolizaSeguroId");
                });

            modelBuilder.Entity("ClinicaApp.Domain.RegistroEnfermeria", b =>
                {
                    b.HasOne("ClinicaApp.Domain.SignosVitales", "Signos")
                        .WithMany()
                        .HasForeignKey("SignosId");
                });
#pragma warning restore 612, 618
        }
    }
}
